2024-10 LLVM developer meeting contents
llvm/www-new pull request #6
Opened 2024-12-22 19:22 UTC by pranavkalpathishankar

Adding 2024 october developer meeting updates

2024-12-29 12:55 UTC, Chaitanya-Shahare requested changes
Can you also add the slides to this repository into the `/static/devmtg/2024-10/` folder, you'll just have to copy and paste the entire folder.

2024-12-29 12:55 UTC, Chaitanya-Shahare commented on assets/jsconfig.json
> +    "..\\themes\\www-template\\assets\\*"
I don't think this change is necessary. Forward slashes should work on windows as well.

2024-12-29 12:55 UTC, Chaitanya-Shahare commented on data/devmtg/2024-10/posters.yml
> +    video_url: "N/A"
Instead of N/A can you just have an empty string, I think that makes more sense & that case is handled in the theme as well.

2024-12-29 23:45 UTC, pranavkalpathishankar commented on assets/jsconfig.json
> +    "..\\themes\\www-template\\assets\\*"
Sure

2024-12-29 23:45 UTC, pranavkalpathishankar commented on data/devmtg/2024-10/posters.yml
> +    video_url: "N/A"
Sure

2024-12-30 00:18 UTC, pranavkalpathishankar commented
> Can you also add the slides to this repository into the `/static/devmtg/2024-10/` folder, you'll just have to copy and paste the entire folder.

Sure

2024-12-31 06:02 UTC, merged

2024-12-31 08:59 UTC, Chaitanya-Shahare commented
#4